name: API test

on:
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    name: API test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Witcher API test
        uses: getjoystick/witcher-action@v0.1.0-prerelease.4
        with:
          source: local
          localConfigPath: ./test/success/root-jsonplaceholder.json
          # Specifying `secretJson` is optional, read `witcher` documentation for more info
          secretJson: ${{ secrets.API_TEST_SECRETS_JSON }}
